### PR TITLE
fix!: [#4] Show overwrite warning for `ahoy init`

### PR DESCRIPTION
**Pull request by ocean**
Fix for #4 

Shows a warning and a confirmation prompt when running `ahoy init`
if an `.ahoy.yml` file already exists in the current directory and
would otherwise be overwritten.

BREAKING CHANGE: The warning prompt requires user input, so this may
require updating of e.g. scripted calls to `ahoy init`. The prompt
can be overruled by passing the "force" flag, e.g.
`ahoy init --force`

If the `--force` flag is passed, the `init` command goes ahead, but a warning message is still shown:

"Warning: '--force' parameter passed, overwriting .ahoy.yml in current directory.".

### CODE REVIEW

**Review by AlexSkrypnyk — APPROVED** [review]
@ocean 
LGTM

Could you please update the description of the PR to explicitly explain if the message is still shown if the `--force` is passed.

**Comment by ocean** [comment]
@AlexSkrypnyk Ok cool. A warning message *is* still shown if you pass the `--force` flag, but the command goes ahead anyway.

Do you reckon I should remove that or still have it?

**Comment by AlexSkrypnyk** [comment]
@ocean 
I think we should still have the message.

**Comment by AlexSkrypnyk** [comment]
@ocean please feel free to merge at your earliest convenience. thank you

**Pull request merged**
