### PR TITLE
chore: migrate to go modules

### PR DESCRIPTION
**Pull request by tianyuanhao**
Users are encouraged to migrate to modules from other dependency management systems since Go 1.14.

Besides, "github.com/codegangsta/cli" is now "github.com/urfave/cli".

Refs #82

### CODE REVIEW

**Comment by tianyuanhao** [comment]
Hi @frankcarey.

I have another commit (tianyuanhao@3406062) that depends on this PR. Do you have any suggestions?

**Comment by frankcarey** [comment]
Right on - I'll take a look this weekend - thanks!

**Comment by frankcarey** [comment]
Note: a couple PRs just got merge that either solve this or at least there is a conflict that needs resolving first. Thanks!

**Comment by ocean** [comment]
Thanks @frankcarey these changes were rolled into my #92 merge along with some more updates 👍 

Thank you very much @tianyuanhao for your contribution 👍 👏  We will have a refreshed version of `ahoy` out soon.

**Pull request closed without merging**
